# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Run File Extension Converter'
Rake::Task.define_task(:run_file_extension_converter) do
  puts <<~PROMPT
    Provide the original extension of the files you would like to change
    (e.g., .jpg, .png, .rb, .py, .ts, .js etc.)
  PROMPT
  original_extension = $stdin.gets&.chomp&.strip

  puts <<~PROMPT
    Provide the target extension of the files you would like to switch to by the change
    (e.g., .jpg, .png, .rb, .py, .ts, .js etc.)
  PROMPT
  target_extension = $stdin.gets&.chomp&.strip

  puts <<~PROMPT
    Provide d(dry_run: default) to make sure what directories and files are to be changed in the extensions first.
    Then, provide e(execution) if you would truly like to change the extensions.
    This operation is cannot be undone, so be alert to your operation!
  PROMPT
  mode = $stdin.gets&.chomp&.strip

  params = { original_extension:, target_extension:, mode: }.reject { |_, value| value&.empty? }

  Application.run(**params)
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
